require "ysd_plugin_booking_analysis/version"

require 'ysd_plugin_booking_analysis/model/ysd_md_booking_analysis_queries'
require 'ysd_plugin_booking_analysis/model/ysd_md_booking_analysis_queries_postgresql'
require 'ysd_plugin_booking_analysis/model/ysd_md_booking_analysis_queries_mysql'
require 'ysd_plugin_booking_analysis/model/ysd_md_booking_analysis_queries_sqlite'
require 'ysd_plugin_booking_analysis/sinatra/ysd_sinatra_booking_analysis'
require 'ysd_plugin_booking_analysis/sinatra/ysd_sinatra_booking_analysis_rest_api'
require 'ysd_plugin_booking_analysis/yito_extension/ysd_plugin_booking_analysis_extension'
require 'ysd_plugin_booking_analysis/ysd_plugin_booking_analysis_init'

module YsdPluginBookingAnalysis
  # Your code goes here...
end
